### ISSUE TITLE
Solo Charts: Tech Debt and Maintenance

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo-charts#12]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/solo-charts/issues/4
- [ ] https://github.com/hashgraph/solo-charts/issues/19
- [ ] https://github.com/hashgraph/solo-charts/issues/20
- [ ] https://github.com/hashgraph/solo-charts/issues/29
- [ ] https://github.com/hashgraph/solo-charts/issues/40
- [ ] https://github.com/hashgraph/solo-charts/issues/42
- [ ] https://github.com/hashgraph/solo-charts/issues/43
- [ ] https://github.com/hashgraph/solo-charts/issues/46
- [ ] https://github.com/hashgraph/solo-charts/issues/48
- [ ] https://github.com/hashgraph/solo-charts/issues/50
- [ ] https://github.com/hashgraph/solo-charts/issues/78
- [ ] https://github.com/hashgraph/solo-charts/issues/79
- [ ] https://github.com/hashgraph/solo-charts/issues/80
- [ ] https://github.com/hashgraph/solo-charts/issues/83
```
