### ISSUE TITLE
Solo Charts: Features

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo-charts#17]
```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/solo-charts/issues/18
- [ ] https://github.com/hashgraph/solo-charts/issues/37
- [ ] https://github.com/hashgraph/solo-charts/issues/55
- [ ] https://github.com/hashgraph/solo-charts/issues/58
- [ ] https://github.com/hashgraph/solo-charts/issues/60
- [ ] https://github.com/hashgraph/solo-charts/issues/81
- [ ] https://github.com/hashgraph/solo-charts/issues/82
- [ ] https://github.com/hashgraph/solo-charts/issues/87
- [ ] https://github.com/hashgraph/solo-charts/issues/89
- [ ] https://github.com/hashgraph/solo-charts/issues/96
```
