### ISSUE TITLE
Charts[Network]: add a `hedera.configMaps.genesisNetworkJson` to the values file and update the `network-node-data-config-cm.yaml` and `network-node-statefulset.yaml` to use it

### ISSUE THREAD

**Issue by jeromy-cannon** [hashgraph/solo-charts#55]
- relates to https://github.com/hashgraph/solo/issues/949

```[tasklist]
### Tasks
- [x] update the values file to initialize `hedera.configMaps.genesisNetworkJson` to an empty string like the other configMaps in that section
- [x] update `network-node-data-config-cm.yaml` to use the new value when writing the configMap
- [x] update `network-node-statefulset.yaml` to use the configMap and mount it with the filename = `genesis-network.json`
```
